cmake_minimum_required(VERSION 3.22.0)

project(figures_project)

add_executable(figures_programm Figures.cpp 
FigureException.cpp 
Figure.cpp 
Triangle.cpp 
Quadrangle.cpp 
EquilateralTriangle.cpp 
IsoscelesTriangle.cpp 
RightAngledTriangle.cpp 
Parallelogram.cpp 
Rectangle.cpp 
Rhomb.cpp 
Square.cpp)